Project/routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\Api\GoogleController;
use App\Http\Controllers\CardProductController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/product/{id}', [App\Http\Controllers\HomeController::class, 'show'])->name('product.detail');
Route::get('/shop/{id}', [App\Http\Controllers\HomeController::class, 'showCate'])->name('category.products');


Route::prefix('auth/google')->name('google.')->group(function () {
    Route::get('login', [GoogleController::class, 'loginWithGoogle'])->name('login');

    Route::any('callback', [GoogleController::class, 'callbackFromGoogle'])->name('callback');
});

//Category
Route::prefix('categories')->middleware('auth')
    ->name('categories.')
    ->controller(CategoryController::class)->group(function(){
    Route::get('/', 'index')
        ->name('index')
        ->middleware('check.permission:category_view');

    Route::post('/','store')
        ->name('store')
        ->middleware('check.permission:category_store');

    Route::get('/create','create')
        ->name('create')
        ->middleware('check.permission:category_create');

    Route::put('/update/{id}','update')
        ->name('update')
        ->middleware('check.permission:category_update');

    Route::get('/edit/{id}','edit')
        ->name('edit')
        ->middleware('check.permission:category_edit');

    Route::delete('/destroy/{id}','destroy')
        ->name('destroy')
        ->middleware('check.permission:category_delete');

    Route::get('/show/{id}','show')
        ->name('show')
        ->middleware('check.permission:category_show');
});

//User
Route::prefix('users')->middleware('auth')->group(function(){
    Route::get('/', [UserController::class, 'index'])
        ->name('users.index')
        ->middleware('check.permission:user_view');

    Route::post('/',[UserController::class, 'store'])
        ->name('users.store')
        ->middleware('check.permission:user_store');

    Route::get('/create',[UserController::class,'create'])
        ->name('users.create')
        ->middleware('check.permission:user_create');

    Route::put('/update/{id}',[UserController::class,'update'])
        ->name('users.update')
        ->middleware('check.permission:user_update');

    Route::get('/edit/{id}',[UserController::class,'edit'])
        ->name('users.edit')
        ->middleware('check.permission:user_edit');

    Route::delete('/destroy/{id}',[UserController::class,'destroy'])
        ->name('users.destroy')
        ->middleware('check.permission:user_delete');

    Route::get('/show/{id}', [UserController::class, 'show'])
        ->name('users.show')
        ->middleware('check.permission:user_show');
});

//Role
Route::middleware('auth')->group(function(){
    Route::get('roles', [RoleController::class, 'index'])
        ->name('roles.index')
        ->middleware('check.permission:role_view');

    Route::post('roles',[RoleController::class, 'store'])
        ->name('roles.store')
        ->middleware('check.permission:role_store');

    Route::get('/roles/create',[RoleController::class,'create'])
        ->name('roles.create')
        ->middleware('check.permission:role_create');

    Route::put('roles/update/{id}',[RoleController::class,'update'])
        ->name('roles.update')
        ->middleware('check.permission:role_update');

    Route::get('roles/edit/{id}',[RoleController::class,'edit'])
        ->name('roles.edit')
        ->middleware('check.permission:role_edit');

    Route::delete('roles/destroy/{id}',[RoleController::class,'destroy'])
        ->name('roles.destroy')
        ->middleware('check.permission:role_delete');

    Route::get('roles/show/{id}', [RoleController::class, 'show'])
        ->name('roles.show')
        ->middleware('check.permission:role_show');

});

//Product
Route::prefix('products')->middleware('auth')->group(function(){
    Route::get('/', [ProductController::class, 'index'])
        ->name('products.index');

    Route::post('/',[ProductController::class, 'store'])
        ->name('products.store')
        ->middleware('check.permission:product_store');

    Route::get('/create',[ProductController::class,'create'])
        ->name('products.create')
        ->middleware('check.permission:product_create');

    Route::put('/update/{id}',[ProductController::class,'update'])
        ->name('products.update')
        ->middleware('check.permission:product_update');

    Route::get('/edit/{id}',[ProductController::class,'edit'])
        ->name('products.edit')
        ->middleware('check.permission:product_edit');

    Route::delete('/destroy/{id}',[ProductController::class,'destroy'])
        ->name('products.destroy')
        ->middleware('check.permission:product_delete');

    Route::get('/show/{id}', [ProductController::class, 'show'])
        ->name('products.show')
        ->middleware('check.permission:product_show');

    Route::get('/list',[ProductController::class,'list'])
        ->name('products.list');
    
    Route::get('category/{id}',[ProductController::class,'listProductByCategory'])
    ->name('listProductByCate');
});

Route::get('test', function () {
    return view('layouts.dasbroard');
})->name('test')->middleware('auth');

Route::get('shop', function () {
    $products = \App\Models\Product::latest('id')->paginate(9);
    return view('layouts.shop',compact('products'));
})->name('shop');

Route::get('detail', function () {
    return view('layouts.detail');
})->name('detail');

Route::get('cart', [CartController::class, 'listCart'])->name('cart');
Route::post('addcart', [HomeController::class, 'addCart'])->name('cart.add');

Route::get('checkout', function () {
    return view('layouts.checkout');
})->name('checkout');

Route::get('contact', function () {
    return view('layouts.contact');
})->name('contact');

Route::get('logingg', function () {
    return view('auth.loginGG');
})->name('loginGG');

Route::prefix('cart/product/{id}')->middleware('auth')->group(function(){
    Route::get('/', [CardProductController::class, 'viewproduct'])
        ->name('detail.index');
});

Route::get('payment', [CartController::class, 'paymentVNP'])->name('payment');
Route::get('vnpay/return', [CartController::class, 'vnpayReturn'])->name('vnpay.return');

Project/app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $table = 'categories';

    protected $fillable = ['name', 'parent_id'];

    public function parentCategory()
    {
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

    public function products()
    {
        return $this->belongsToMany(
            Product::class,
            'category_product',
            'category_id',
            'product_id'
        );
    }

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('name','Like', "%$name%") : null;
    }
}

Project/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest\CreateCategoryRequest;
use App\Http\Requests\CategoryRequest\UpdateCategoryRequest;
use App\Models\Category;
use App\Services\CategoryService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\View;

class CategoryController extends Controller
{
    protected $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    public function index(Request $request)
    {
        $categories = $this->categoryService->search($request);
        return view('categories.index', compact('categories'));
    }

    public function create()
    {

        return view('categories.create');
    }

    public function store(CreateCategoryRequest $request)
    {
        $this->categoryService->store($request);
        return redirect()->route('categories.index');
    }

    public function show($id)
    {
        $category = $this->categoryService->findOrFail($id);
        return view('categories.show',compact('category'));
    }

    public function edit($id)
    {
        $category = $this->categoryService->findOrFail($id);
        return view('categories.edit',compact('category'));
    }

    public function update(UpdateCategoryRequest $request,$id)
    {
        $category = $this->categoryService->findOrFail($id);
        $category->update($request->all());
        return redirect()->route('categories.index');
    }

    public function destroy(Request $request,$id)
    {
        $category = $this->categoryService->findOrFail($id);
        $category->delete($request->all());
        return redirect()->route('categories.index');
    }
}

Project/resources/views/categories/create.blade.php
@extends('layouts.index')

@section('content')

    <div class="container-fluid py-4">
        <div class="card">
            <div class="card-header pb-0">
                <div class="d-flex align-items-center">
                    <p class="mb-0">Create</p>
                </div>
            </div>
            <form action="{{route('categories.store')}}" method="POST">
                @csrf
                <div class="card-body">
                    <p class="text-uppercase text-sm">Create Information</p>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="example-text-input" class="form-control-label">Category</label>
                                <input class="form-control" type="text" name="name" value="{{old('name')}}" placeholder="Username ...">
                                @error('name')
                                <span id="content-error" class="error text-danger"
                                      style="display: block">
                                {{ $message }}
                                </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <hr class="horizontal dark">
                    <button class="btn btn-dark ">Submit</button>
                </div>
            </form>
        </div>
    </div>
@endsection

Project/resources/views/categories/createparentcategory.blade.php
@extends('layouts.app2')

@section('content')
    <div class="container-fluid py-4">
        <div class="card">
            <div class="card-header pb-0">
                <div class="d-flex align-items-center">
                    <p class="mb-0">Create</p>
                </div>
            </div>
            <form action="{{route('categories.store')}}" method="POST">
                @csrf
                <div class="card-body">
                    <p class="text-uppercase text-sm">Create Information</p>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                {{--                                <label for="example-text-input" class="form-control-label">Parent ID</label>--}}
                                {{--                                <input class="form-control" type="text" name="parent_id" value="{{old('parent_id')}}"  placeholder="Parent ID ...">--}}
                                <label for="">Parent Category</label>
                                <br>
                                <select class="form-select" id="parentIdCreate" name="parent_id" >
                                    @foreach($categories as $category)
                                        <option value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
                                @error('parent_id')
                                <span id="content-error" class="error text-danger"
                                      style="display: block">
                                {{ $message }}
                                </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <hr class="horizontal dark">
                    <button class="btn btn-dark ">Submit</button>
                </div>
            </form>
        </div>
    </div>
@endsection

Project/resources/views/categories/edit.blade.php
@extends('layouts.index')
@section('content')
    <div class="container-fluid py-4">
        <div class="card">
            <div class="card-header pb-0">
                <div class="d-flex align-items-center">
                    <p class="mb-0">Edit</p>
                </div>
            </div>
            <form action="{{route('categories.update',$category->id)}}" method="POST">
                @method('PUT')
                @csrf
                <div class="card-body">
                    <p class="text-uppercase text-sm">Edit Information</p>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="example-text-input" class="form-control-label">Name</label>
                                <br>
                                <input class="form-control" type="text" name="name" placeholder="" value="{{$category->name}}">
                                @error('name')
                                <span id="content-error" class="error text-danger"
                                      style="display: block">
                                {{ $message }}
                            </span>
                                @enderror
                            </div>
                        </div>
                    </div>
                    <hr class="horizontal dark">
                    <button type="submit" class="btn btn-success">Update</button>
                    <script>
                        function goBack()
                        {
                            window.history.back()
                        }
                    </script>
                    <input type="button" class="btn btn-danger" value="Return" onclick="goBack()"/>
                </div>
            </form>
        </div>
    </div>
@endsection

Project/resources/views/categories/index.blade.php
@extends('layouts.index')
@section('title', 'Category')
@section('content')
    <div class="container-fluid py-4">
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header pb-0">
                        <h6>Category table</h6>
                        @if (session('message'))
                            <div class="alert alert-success" role="alert">
                                {{session('message')}}
                            </div>
                        @endif
                        @hasPermission('category_create')
                        <a style="text-decoration: none" href="{{route('categories.create')}}"><button class="btn btn-success">Create</button></a>
                        @endhasPermission
                    <form action="{{route('categories.index')}}" method="get" class="card p-3 py-4 mt-3">
                        <div class="row g-3 mt-2">
                            <div class="col-md-6">
                                <input type="search" class="form-control" placeholder="Enter Category ..." name="name" value="{{ request()->input('name') }}">
                            </div>
                            <div class="col-md-3">
                                <button type="submit" class="btn btn-secondary btn-success">Search Results</button>
                            </div>
                        </div>
                    </form>
                    </div>
                    <div class="card-body px-0 pt-0 pb-2">
                        <div class="table-responsive p-0">
                            <table class="table align-items-center mb-0">
                                <thead>
                                <tr>
                                    <th class="text-secondary opacity-7" style="text-align: center">ID</th>
                                    <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                        Name
                                    </th>
                                    <th style="width: 20%" class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                        Actions
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($categories as $item)
                                    <tr>
                                        <td>
                                            <p style="text-align: center">{{ $loop->index+1  }}</p>
                                        </td>
                                        <td>
                                            <div class="d-flex px-2 py-1">
                                                <div class="d-flex flex-column justify-content-center">
                                                    <h6 class="mb-0 text-sm">{{$item->name}}</h6>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <table>
                                                <tr>
                                                    <td>
                                                        <form id="deleteform{{ $item->id }}" action="{{route("categories.destroy", $item->id)}}" method="POST">
                                                            @method("DELETE")
                                                            @csrf
                                                        </form>
                                                        <button data-form="deleteform{{ $item->id }}" type="submit" class="btn btn-delete btn-danger">Delete</button>
                                                    </td>
{{--                                                    <td>--}}
{{--                                                        <button class="deleteCate btn btn-danger"><i class="fa-solid fa-trash-can"></i></button>--}}
{{--                                                    </td>--}}
                                                    <td>
                                                        @hasPermission('category_edit')
                                                        <button class="btn btn-warning">
                                                            <a class="text-decoration-none text-reset"
                                                               href="{{route('categories.edit',$item->id)}}">Edit</a>
                                                        </button>
                                                        @endhasPermission
                                                    </td>
                                                    <td>
                                                        @hasPermission('category_show')
                                                        <button type="button" class="btn btn-info">
                                                            <a class="text-decoration-none text-reset"
                                                               href="{{route('categories.show',$item->id)}}">View</a>
                                                        </button>
                                                        @endhasPermission
                                                    </td>
                                                </tr>
                                            </table>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="d-flex justify-content-center">{{ $categories->links('pagination::bootstrap-4') }}</div>
@endsection
@section("script")
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        $(function () {
            $(document).on("click", ".btn-delete", function () {
                let formID = $(this).data("form");
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        $(`#${formID}`).submit();
                    }
                })
            })
        })

        $("document").ready(function () {
            setTimeout(function () {
                $(".alert-success").remove();
            }, 2000);
        });
    </script>
@endsection

Project/resources/views/categories/show.blade.php
@extends('layouts.index')

@section('content')
    <div class="container-fluid py-4">
        <div class="card">
            <div class="card-body pt-4 p-3">
                <ul class="list-group">
                    <li class="list-group-item border-0 d-flex p-4 mb-2 bg-gray-100 border-radius-lg">
                        <div class="d-flex flex-column">
                            <span class="mb-2 text-xs">Id: <span class="text-dark font-weight-bold ms-sm-2">{{$category->id}}</span></span>
                            <span class="mb-2 text-xs">Name: <span class="text-dark ms-sm-2 font-weight-bold">{{$category->name}}</span></span>
                            <span class="text-xs">Parent Id: <span class="text-dark ms-sm-2 font-weight-bold">{{$category->parent_id}}</span></span>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
@endsection